CREATE TABLE IF NOT EXISTS data_centers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  company TEXT NOT NULL,
  company_type TEXT NOT NULL,
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  country TEXT NOT NULL DEFAULT 'USA',
  capacity_mw REAL,
  estimated_annual_gwh REAL,
  water_usage_million_gallons REAL,
  status TEXT NOT NULL,
  year_opened INTEGER,
  year_planned INTEGER,
  investment_billions REAL,
  acreage REAL,
  primary_models TEXT,
  community_impact TEXT,
  community_resistance INTEGER DEFAULT 0,
  grid_risk TEXT,
  renewable_percent INTEGER,
  notes TEXT
);
